using System.Windows.Controls;
using System.Windows.Controls.Primitives;

namespace RHToolkit.Behaviors
{
    public class DataGridBehavior
    {
        #region DisplayRowNumber

        public static readonly DependencyProperty DisplayRowNumberProperty =
            DependencyProperty.RegisterAttached(
                "DisplayRowNumber",
                typeof(bool),
                typeof(DataGridBehavior),
                new FrameworkPropertyMetadata(false, OnDisplayRowNumberChanged)
            );

        public static bool GetDisplayRowNumber(DependencyObject target) =>
            (bool)target.GetValue(DisplayRowNumberProperty);

        public static void SetDisplayRowNumber(DependencyObject target, bool value) =>
            target.SetValue(DisplayRowNumberProperty, value);

        private static void OnDisplayRowNumberChanged(DependencyObject target, DependencyPropertyChangedEventArgs e)
        {
            if (target is not DataGrid dataGrid) return;

            if ((bool)e.NewValue)
            {
                void LoadedRowHandler(object? sender, DataGridRowEventArgs ea)
                {
                    if (!GetDisplayRowNumber(dataGrid))
                    {
                        dataGrid.LoadingRow -= LoadedRowHandler;
                        return;
                    }
                    ea.Row.Header = ea.Row.GetIndex() + 1;
                }

                dataGrid.LoadingRow += LoadedRowHandler;

                void ItemsChangedHandler(object? sender, ItemsChangedEventArgs ea)
                {
                    if (!GetDisplayRowNumber(dataGrid))
                    {
                        dataGrid.ItemContainerGenerator.ItemsChanged -= ItemsChangedHandler;
                        return;
                    }

                    foreach (var row in GetVisualChildCollection<DataGridRow>(dataGrid))
                    {
                        row.Header = row.GetIndex() + 1;
                    }
                }

                dataGrid.ItemContainerGenerator.ItemsChanged += ItemsChangedHandler;
            }
        }

        #endregion // DisplayRowNumber

        #region Get Visuals

        private static List<T> GetVisualChildCollection<T>(object parent) where T : Visual
        {
            var visualCollection = new List<T>();
            if (parent is DependencyObject depObj)
            {
                GetVisualChildCollection(depObj, visualCollection);
            }
            return visualCollection;
        }

        private static void GetVisualChildCollection<T>(DependencyObject parent, List<T> visualCollection) where T : Visual
        {
            var count = VisualTreeHelper.GetChildrenCount(parent);
            for (var i = 0; i < count; i++)
            {
                var child = VisualTreeHelper.GetChild(parent, i);
                if (child is T tChild)
                {
                    visualCollection.Add(tChild);
                }
                GetVisualChildCollection(child, visualCollection);
            }
        }

        #endregion // Get Visuals

        #region AdjustAutoGeneratedColumnMinWidth

        public static readonly DependencyProperty AdjustAutoGeneratedColumnMinWidthProperty =
            DependencyProperty.RegisterAttached("AdjustAutoGeneratedColumnMinWidth", typeof(bool), typeof(DataGridBehavior), new PropertyMetadata(false, OnAdjustAutoGeneratedColumnMinWidthChanged));

        public static bool GetAdjustAutoGeneratedColumnMinWidth(DependencyObject obj)
        {
            return (bool)obj.GetValue(AdjustAutoGeneratedColumnMinWidthProperty);
        }

        public static void SetAdjustAutoGeneratedColumnMinWidth(DependencyObject obj, bool value)
        {
            obj.SetValue(AdjustAutoGeneratedColumnMinWidthProperty, value);
        }

        private static void OnAdjustAutoGeneratedColumnMinWidthChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is DataGrid dataGrid)
            {
                if ((bool)e.NewValue)
                {
                    dataGrid.AutoGeneratedColumns += DataGrid_AutoGeneratedColumns;
                }
                else
                {
                    dataGrid.AutoGeneratedColumns -= DataGrid_AutoGeneratedColumns;
                }
            }
        }

        private static void DataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
        {
            if (sender is DataGrid dataGrid)
            {
                foreach (var column in dataGrid.Columns)
                {
                    var headerText = column.Header?.ToString() ?? string.Empty;
                    var headerTextBlock = new TextBlock { Text = headerText };
                    headerTextBlock.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));

                    double margin = 20;
                    column.MinWidth = headerTextBlock.DesiredSize.Width + margin;

                    // Set the column width to Auto initially
                    column.Width = DataGridLength.Auto;
                }

                dataGrid.LayoutUpdated += DataGrid_LayoutUpdated;
            }
        }

        private static void DataGrid_LayoutUpdated(object? sender, EventArgs e)
        {
            if (sender is DataGrid dataGrid)
            {
                foreach (var column in dataGrid.Columns)
                {
                    // Calculate the desired width with a margin
                    double desiredWidth = column.ActualWidth < column.MinWidth ? column.MinWidth : column.ActualWidth;
                    double margin = 20;
                    desiredWidth += margin;

                    // Apply the width to the column
                    column.Width = new DataGridLength(desiredWidth);
                }
            }
        }

        #endregion //Column Min Width

        #region SelectedCell

        public static readonly DependencyProperty SelectedCellProperty =
            DependencyProperty.RegisterAttached(
                "SelectedCell",
                typeof(Point),
                typeof(DataGridBehavior),
                new FrameworkPropertyMetadata(new Point(-1, -1), OnSelectedCellChanged));

        public static Point GetSelectedCell(DependencyObject obj)
        {
            return (Point)obj.GetValue(SelectedCellProperty);
        }

        public static void SetSelectedCell(DependencyObject obj, Point value)
        {
            obj.SetValue(SelectedCellProperty, value);
        }

        private static void OnSelectedCellChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is DataGrid dataGrid)
            {
                Point cell = (Point)e.NewValue;
                if (cell.X >= 0 && cell.Y >= 0 && dataGrid.ItemsSource != null)
                {
                    if (dataGrid.Items.Count > (int)cell.X && dataGrid.Columns.Count > (int)cell.Y)
                    {
                        // Select the cell
                        dataGrid.SelectedCells.Clear();
                        DataGridCellInfo cellInfo = new(
                            dataGrid.Items[(int)cell.X], dataGrid.Columns[(int)cell.Y]);
                        dataGrid.SelectedCells.Add(cellInfo);

                        // Scroll to the selected cell
                        dataGrid.ScrollIntoView(cellInfo.Item);
                    }
                }
            }
        }
        #endregion

        #region ScrollIntoView
        public static readonly DependencyProperty EnableScrollIntoViewProperty =
            DependencyProperty.RegisterAttached("EnableScrollIntoView", typeof(bool), typeof(DataGridBehavior), new PropertyMetadata(false, OnEnableScrollIntoViewChanged));

        public static bool GetEnableScrollIntoView(DependencyObject obj)
        {
            return (bool)obj.GetValue(EnableScrollIntoViewProperty);
        }

        public static void SetEnableScrollIntoView(DependencyObject obj, bool value)
        {
            obj.SetValue(EnableScrollIntoViewProperty, value);
        }

        private static void OnEnableScrollIntoViewChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is DataGrid dataGrid)
            {
                if ((bool)e.NewValue)
                {
                    dataGrid.SelectionChanged += DataGrid_SelectionChanged;
                }
                else
                {
                    dataGrid.SelectionChanged -= DataGrid_SelectionChanged;
                }
            }
        }

        private static void DataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (sender is DataGrid dataGrid)
            {
                if (dataGrid.SelectedItem != null)
                {
                    dataGrid.Dispatcher.InvokeAsync(() =>
                    {
                        if (dataGrid.SelectedItem != null)
                        {
                            dataGrid.ScrollIntoView(dataGrid.SelectedItem);
                        }
                    }, DispatcherPriority.ContextIdle);
                }
            }
        }


        #endregion

        #region DisableHorizontalScrollOnEditOrSelection

        public static readonly DependencyProperty DisableHorizontalScrollOnEditOrSelectionProperty =
            DependencyProperty.RegisterAttached(
                "DisableHorizontalScrollOnEditOrSelection",
                typeof(bool),
                typeof(DataGridBehavior),
                new FrameworkPropertyMetadata(false, OnDisableHorizontalScrollOnEditOrSelectionChanged)
            );

        public static bool GetDisableHorizontalScrollOnEditOrSelection(DependencyObject target) =>
            (bool)target.GetValue(DisableHorizontalScrollOnEditOrSelectionProperty);

        public static void SetDisableHorizontalScrollOnEditOrSelection(DependencyObject target, bool value) =>
            target.SetValue(DisableHorizontalScrollOnEditOrSelectionProperty, value);

        private static void OnDisableHorizontalScrollOnEditOrSelectionChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is DataGrid dataGrid)
            {
                if ((bool)e.NewValue)
                {
                    dataGrid.SelectedCellsChanged += DataGrid_SelectedCellsChanged;
                    dataGrid.PreparingCellForEdit += DataGrid_PreparingCellForEdit;
                }
                else
                {
                    dataGrid.SelectedCellsChanged -= DataGrid_SelectedCellsChanged;
                    dataGrid.PreparingCellForEdit -= DataGrid_PreparingCellForEdit;
                }
            }
        }

        private static void DataGrid_SelectedCellsChanged(object sender, SelectedCellsChangedEventArgs e)
        {
            // Prevent horizontal scrolling on cell selection
            if (sender is DataGrid dataGrid && e.AddedCells.Count > 0)
            {
                var firstAddedCell = e.AddedCells[0];
                if (firstAddedCell.Column != null)
                {
                    dataGrid.ScrollIntoView(firstAddedCell.Item, firstAddedCell.Column);
                }
            }
        }


        private static void DataGrid_PreparingCellForEdit(object? sender, DataGridPreparingCellForEditEventArgs e)
        {
            // Prevent horizontal scrolling on cell edit
            if (sender is DataGrid dataGrid)
            {
                dataGrid.ScrollIntoView(e.Row.Item, dataGrid.Columns[e.Column.DisplayIndex]);
            }
        }

        #endregion // DisableHorizontalScrollOnEditOrSelection

        #region WrapTextOnShiftEnter

        public static readonly DependencyProperty WrapTextOnShiftEnterProperty =
            DependencyProperty.RegisterAttached(
                "WrapTextOnShiftEnter",
                typeof(bool),
                typeof(DataGridBehavior),
                new FrameworkPropertyMetadata(false, OnWrapTextOnShiftEnterChanged)
            );

        public static bool GetWrapTextOnShiftEnter(DependencyObject target) =>
            (bool)target.GetValue(WrapTextOnShiftEnterProperty);

        public static void SetWrapTextOnShiftEnter(DependencyObject target, bool value) =>
            target.SetValue(WrapTextOnShiftEnterProperty, value);

        private static void OnWrapTextOnShiftEnterChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is DataGrid dataGrid)
            {
                if ((bool)e.NewValue)
                {
                    dataGrid.PreviewKeyDown += DataGrid_PreviewKeyDown;
                }
                else
                {
                    dataGrid.PreviewKeyDown -= DataGrid_PreviewKeyDown;
                }
            }
        }

        private static void DataGrid_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter && (Keyboard.IsKeyDown(Key.LeftShift) || Keyboard.IsKeyDown(Key.RightShift)))
            {
                DataGrid dataGrid = (DataGrid)sender;
                var cell = dataGrid.CurrentCell;

                if (cell.Column.GetCellContent(cell.Item) is not TextBox editingElement)
                    return;

                string text = editingElement.Text;
                int caretIndex = editingElement.CaretIndex;

                string newText = string.Concat(text.AsSpan(0, caretIndex), Environment.NewLine, text.AsSpan(caretIndex));

                editingElement.Text = newText;
                editingElement.CaretIndex = caretIndex + Environment.NewLine.Length;

                e.Handled = true;
            }
        }

        #endregion // WrapTextOnShiftEnter
    }
}
