name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Rusty Hearts Toolkit
        run: dotnet publish ./RHToolkit.sln --configuration Release --self-contained false --runtime win-x64 /p:PublishSingleFile=false /p:PublishDir=./publish/RHToolkit
      
      - name: Zip output files
        run: Compress-Archive -Path "./publish/RHToolkit" -DestinationPath RustyHearts-Toolkit.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rusty Hearts Toolkit
          path: RustyHearts-Toolkit.zip
