name: Release
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Build with --self-contained false
      - name: Build Rusty Hearts Toolkit (No Self-Contained)
        run: dotnet publish ./RHToolkit.sln --configuration Release --self-contained false --runtime win-x64 /p:PublishSingleFile=false /p:PublishDir=./publish/RustyHearts-Toolkit_framework-dependent

      - name: Install 7-Zip
        run: choco install 7zip -y
      - name: Unzip Resources.zip
        run: 7z x Resources.zip -o"./publish/RustyHearts-Toolkit_framework-dependent"

      - name: Zip output files (No Self-Contained)
        run: Compress-Archive -Path "./publish/RustyHearts-Toolkit_framework-dependent" -DestinationPath RustyHearts-Toolkit-Framework-Dependent.zip

      # Build with --self-contained true
      - name: Build Rusty Hearts Toolkit (Self-Contained)
        run: dotnet publish ./RHToolkit.sln --configuration Release --self-contained true --runtime win-x64 /p:PublishSingleFile=false /p:PublishDir=./publish/RustyHearts-Toolkit_self-contained

      - name: Unzip Resources.zip
        run: 7z x Resources.zip -o"./publish/publish/RustyHearts-Toolkit_self-contained"

      - name: Zip output files (Self-Contained)
        run: Compress-Archive -Path "./publish/RustyHearts-Toolkit_self-contained" -DestinationPath RustyHearts-Toolkit-SelfContained.zip

      - name: Get version from compiled assembly
        id: version
        run: |
          $version = (Get-Command "./publish/RustyHearts-Toolkit_framework-dependent/Rusty Hearts Toolkit.dll").FileVersionInfo.FileVersion
          echo "::set-output name=version::$version"

      # Create Release and Upload Assets using softprops/action-gh-release
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          body: Automated pre-release created by GitHub Actions.
          draft: true
          prerelease: true
          files: |
            ./RustyHearts-Toolkit-Framework-Dependent.zip
            ./RustyHearts-Toolkit-SelfContained.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
